# GitHub dependabot config, see docs below
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: pip
    directory: "/api"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: daily
