version: "3"
services:
  api:
    image: ttbud-api
    build:
      context: api
      args:
        DEV: "true"
    working_dir: /app/
    command: python -u -m watchgod main.main
    # watchgod will drop all stdout without a tty
    tty: true
    environment:
      ENVIRONMENT:
      JSON_LOGS:
      DOMAIN:
      SCOUT_KEY:
      SCOUT_MONITOR:
      USE_SSL: "true"
      SSL_CRT_FILE: /certs/ttbud.local.pem
      SSL_KEY_FILE: /certs/ttbud.local-key.pem
      PORT: ${API_WEBSOCKET_PORT}
      ROOM_STORE_DIR: /var/ttbud/rooms
      USE_REDIS:
      # We don't set up ssl certs for redis local dev
      REDIS_SSL_VALIDATION: none
      REDIS_URL: redis://db
    volumes:
      - ./api:/app
      - ./certs:/certs
    ports:
      - ${API_WEBSOCKET_PORT}:${API_WEBSOCKET_PORT}
  web:
    image: ttbud-web
    build: web
    command: yarn run start
    environment:
      REACT_APP_DOMAIN: ${DOMAIN}
      REACT_APP_API_WEBSOCKET_PORT: ${API_WEBSOCKET_PORT}
      PORT: ${WEB_HTTP_PORT}
      HTTPS: "true"
      SSL_CRT_FILE: /certs/ttbud.local.pem
      SSL_KEY_FILE: /certs/ttbud.local-key.pem
    user: ${WEB_USER:-1000}
    tty: true
    ports:
      - ${WEB_HTTP_PORT}:${WEB_HTTP_PORT}
    volumes:
      - ./web:/app
      - ./certs:/certs
  db:
    image: redis:6.0.4
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
volumes:
  static-assets:
  certs:
  rooms:
