version: '3'
services:
  api:
    image: ttbud-api
    build: api
    environment:
      DOMAIN:
      PORT: ${API_WEBSOCKET_PORT}
      ROOM_STORE_DIR: /var/ttbud/rooms
    volumes:
      - rooms:/var/ttbud/rooms
  web:
    image: ttbud-web
    build: web
    environment:
      REACT_APP_DOMAIN: ${DOMAIN}
      REACT_APP_API_WEBSOCKET_PORT: ${API_WEBSOCKET_PORT}
    command: yarn run build
    volumes:
      - static-assets:/app/build
  ingress:
    image: abiosoft/caddy
    environment:
      DOMAIN: 
      CERT_CONFIG:
      API_WEBSOCKET_PORT:
      ACME_AGREE: 'true'
    volumes:
      - static-assets:/var/www/ttbud/web
      - ./infra/ingress/Caddyfile:/etc/Caddyfile
      - certs:/root/.caddy
    ports:
      - 80:80
      - 443:443
      - 1234:1234
volumes:
  static-assets:
  certs:
  rooms:
