version: '3'
services:
  api:
    image: ttbud-api
    build: api
    environment:
      DOMAIN:
      API_HTTP_PORT:
      API_WEBSOCKET_PORT:
  web:
    image: ttbud-web
    build: web
    command: yarn run build
    volumes:
      - static-assets:/var/www/ttbud/web
  ingress:
    image: abiosoft/caddy
    environment:
      DOMAIN:
      CERT_CONFIG:
      API_HTTP_PORT:
      API_WEBSOCKET_PORT:
      ACME_AGREE: 'true'
    volumes:
      - static-assets:/var/www/ttbud/web
      - ./infra/ingress/Caddyfile:/etc/Caddyfile
      - certs:/root/.caddy
    ports:
      - 80:80
      - 443:443
      - 1234:1234
volumes:
  static-assets:
  certs:
