version: "3"
services:
  api:
    image: ttbud-api
    build: api
    environment:
      ENVIRONMENT:
      JSON_LOGS:
      DOMAIN:
      SCOUT_KEY:
      SCOUT_MONITOR:
      PORT: ${API_WEBSOCKET_PORT}
      ROOM_STORE_DIR: /var/ttbud/rooms
      USE_REDIS:
      # We don't set up ssl certs for redis local dev
      REDIS_SSL_VALIDATION: none
      REDIS_URL: redis://db
    volumes:
      - rooms:/var/ttbud/rooms
  web:
    image: ttbud-web
    build: web
    environment:
      REACT_APP_DOMAIN: ${DOMAIN}
      REACT_APP_API_WEBSOCKET_PORT: ${API_WEBSOCKET_PORT}
    command: yarn run build
    volumes:
      - static-assets:/app/build
  ingress:
    image: abiosoft/caddy
    environment:
      DOMAIN:
      CERT_CONFIG:
      API_WEBSOCKET_PORT:
      ACME_AGREE: "true"
    volumes:
      - static-assets:/var/www/ttbud/web
      - ./infra/ingress/Caddyfile:/etc/Caddyfile
      - certs:/root/.caddy
    ports:
      - 80:80
      - 443:443
      - 1234:1234
  db:
    image: redis:6.0.4
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
volumes:
  static-assets:
  certs:
  rooms:
