version: 2
jobs:
  api:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo/api
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            # Restore the cache with the exact dependencies,
            - api-deps-v2-{{ checksum "poetry.lock" }}
            # or, failing that, just the most recent cache entry
            - api-deps-v2
      - run:
          name: Configure Poetry
          command: poetry config virtualenvs.in-project true && poetry config virtualenvs.path .venv
      - run:
          name: Install Deps
          command: poetry install
      - save_cache:
          key: api-deps-v2-{{ checksum "poetry.lock" }}
          paths:
            - .venv
      - run:
          name: Check Code Format
          command: poetry run black -S src tests main.py --check
      - run:
          name: Typecheck
          command: poetry run mypy src tests main.py
      - run:
          name: Lint
          command: poetry run flake8 src tests main.py
      - run:
          name: Run Tests
          command: poetry run pytest tests --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
  web:
    docker:
      - image: node:12
    working_directory: ~/repo/web
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            # Restore the cache with the exact dependencies,
            - web-deps-v1-{{ checksum "yarn.lock" }}
            # or, failing that, just the most recent cache entry
            - web-deps-v1
      - run:
          name: Install Deps
          command: yarn install
      - save_cache:
          key: web-deps-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Check Style
          command: yarn run checkstyle
      - run:
          name: Typecheck
          command: yarn run typecheck
      - run:
          name: Run Tests
          environment:
            - JEST_JUNIT_OUTPUT_DIR: test-results
            - REACT_APP_DOMAIN: localhost
            - REACT_APP_API_WEBSOCKET_PORT: 1234
          command: yarn run test -- --reporters=default --reporters=jest-junit
      - store_test_results:
          path: test-results
workflows:
  version: 2
  all:
    jobs:
      - api
      - web
