version: 2
jobs:
  api:
    docker:
      - image: python:3.7
    working_directory: ~/repo/api
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: api-deps-v1-{{ checksum "requirements.txt" }}
      - run:
          name: Activate virtualenv
          command: |
            python -m venv venv
            . ./venv/bin/activate
            PYTHONPATH=./src/:$PYTHONPATH
            export PYTHONPATH
      - run:
          name: Install Deps
          command: pip install -r requirements.txt
      - save_cache:
          key: api-deps-v1-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - run:
          name: Check Code Format
          command: black -S src tests --check
      - run:
          name: Run Tests
          command: pytest tests --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
  web:
    docker:
      - image: node:12
    working_directory: ~/repo/web
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: web-deps-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install Deps
          command: yarn install
      - save_cache:
          key: web-deps-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Check Style
          command: yarn run checkstyle
      - run:
          name: Run Tests
          environment:
            - JEST_JUNIT_OUTPUT_DIR: test-results
          command: yarn run test -- --reporters=default --reporters=jest-junit
      - store_test_results:
          path: test-results
workflows:
  version: 2
  all:
    jobs:
      - api
      - web
