[tool.poetry]
name = "ttbud"
version = "1.2"
description = "Your virtual table friend"
authors = ["Stephen Johnson <github@sjoh.net>"]

[tool.poetry.dependencies]
python = "^3.8"
websockets = "^8.1"
dacite = "^1.5.0"
aioredis = "^1.3.1"
timber = "^2.1.0"
scout_apm = "^2.14.2"

[tool.poetry.dev-dependencies]
pytest = "^5.4"
black = "^19.10b0"
pytest-mock = "^3.1.0"
pytest-asyncio = "^0.11.0"
mypy = "^0.770"
flake8 = "^3.7.9"
watchgod = "^0.6"
fakeredis = "^1.4.1"
pytest-lazy-fixture = "^0.6.3"
locust = "^1.0.3"
# Need a synchronous websocket client for interacting with the API via locust
# locust does not support asyncio
websocket_client = "^0.57.0"
# fakeredis uses it for redis lua support
lupa = "^1.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
