[tool.poetry]
name = "ttbud"
version = "1.2"
description = "Your virtual table friend"
authors = ["Stephen Johnson <github@sjoh.net>"]

[tool.poetry.dependencies]
python = "^3.8"
websockets = "^8.1"
dacite = "^1.5.0"
timber = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4"
black = "^19.10b0"
pytest-mock = "^3.1.0"
pytest-asyncio = "^0.11.0"
mypy = "^0.770"
flake8 = "^3.7.9"
watchgod = "^0.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
